---

- hosts: all
  become: true
  gather_facts: false

  vars:
    ansible_user: ec2-user

  tasks:
    - name: Waiting for SSH connection
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 300


- name: Configuring instance and installing apps
  hosts: all
  become: true

  vars:
    ansible_user: ec2-user

  tasks:

    - name: Install docker
      shell: "amazon-linux-extras install docker -y"

    - name: Iniciate and enable docker
      service:
        name: docker
        enabled: true
        state: started

    - name: Add user to Docker's group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install docker-compose
      pip:
        name: docker-compose
        executable: pip3

    - name: Adding docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: /home/ec2-user
        owner: root
        group: root
        mode: "0644"

    - name: Deploying 2048's app
      community.docker.docker_compose:
        project_src: /home/ec2-user/
        pull: true
      vars:
        ansible_python_interpreter: /usr/bin/python3
